# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# admin
User.create(username: "admin", email: "admin@admin.com", password: "11111111", admin: true)

# sample skills
Skill.create(name: "JavaScript", description: "'It is a very good height indeed!' said the Caterpillar angrily, rearing itself upright as it spoke (it was exactly three inches high).
'But I'm not used to it!' pleaded poor Alice in a piteous tone. And she thought of herself, 'I wish the creatures wouldn't be so easily offended!'", svg_url: "http://cursohtml5js.com/js.png")
Skill.create(name: "Ruby", description: "'It is a very good height indeed!' said the Caterpillar angrily, rearing itself upright as it spoke (it was exactly three inches high).
'But I'm not used to it!' pleaded poor Alice in a piteous tone. And she thought of herself, 'I wish the creatures wouldn't be so easily offended!'", svg_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/198px-Ruby_logo.svg.png")
Skill.create(name: "Ember", description: "'It is a very good height indeed!' said the Caterpillar angrily, rearing itself upright as it spoke (it was exactly three inches high).
'But I'm not used to it!' pleaded poor Alice in a piteous tone. And she thought of herself, 'I wish the creatures wouldn't be so easily offended!'", svg_url: "http://carefullycrafted.net/images/Ember.js_Logo_and_Mascot.png")
Skill.create(name: "Ruby on Rails", description: "'It is a very good height indeed!' said the Caterpillar angrily, rearing itself upright as it spoke (it was exactly three inches high).
'But I'm not used to it!' pleaded poor Alice in a piteous tone. And she thought of herself, 'I wish the creatures wouldn't be so easily offended!'", svg_url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/Ruby_on_Rails.svg/791px-Ruby_on_Rails.svg.png")

#sample posts
Post.create(title: "A lonely impulse of delight...", content: "'I dare say you're wondering why I don't put my arm round your waist,'  the Duchess said after a pause: 'the reason is, that I'm doubtful about  the temper of your flamingo. Shall I try the experiment?' 'HE might bite,' Alice cautiously replied, not feeling at all anxious to  have the experiment tried. 'Very true,' said the Duchess: 'flamingoes and mustard both bite. And  the moral of that is 'Birds of a feather flock together.' 'Only mustard isn't a bird,' Alice remarked.")

Post.create(title: "YAWP!", content: "'Tis so,' said the Duchess: 'and the moral of that is'Oh, 'tis love,  'tis love, that makes the world go round!' 'Somebody said,' Alice whispered, 'that it's done by everybody minding  their own business!' 'Ah, well! It means much the same thing,' said the Duchess, digging her  sharp little chin into Alice's shoulder as she added, 'and the moral  of THAT is'Take care of the sense, and the sounds will take care of  themselves.' 'How fond she is of finding morals in things!' Alice thought to herself.")

Post.create(title: "The world forgetting, by the world forgot.", content: "Down, down, down. There was nothing else to do, so Alice soon began  talking again. 'Dinah'll miss me very much to-night, I should think!'  (Dinah was the cat.) 'I hope they'll remember her saucer of milk at  tea-time. Dinah my dear! I wish you were down here with me! There are no  mice in the air, I'm afraid, but you might catch a bat, and that's very  like a mouse, you know. But do cats eat bats, I wonder?' And here Alice  began to get rather sleepy, and went on saying to herself, in a dreamy  sort of way, 'Do cats eat bats? Do cats eat bats?' and sometimes, 'Do  bats eat cats?' for, you see, as she couldn't answer either question,  it didn't much matter which way she put it. She felt that she was dozing  off, and had just begun to dream that she was walking hand in hand with  Dinah, and saying to her very earnestly, 'Now, Dinah, tell me the truth:  did you ever eat a bat?' when suddenly, thump! thump! down she came upon  a heap of sticks and dry leaves, and the fall was over. Alice was not a bit hurt, and she jumped up on to her feet in a moment:  she looked up, but it was all dark overhead; before her was another  long passage, and the White Rabbit was still in sight, hurrying down it.  There was not a moment to be lost: away went Alice like the wind, and  was just in time to hear it say, as it turned a corner, 'Oh my ears  and whiskers, how late it's getting!' She was close behind it when she  turned the corner, but the Rabbit was no longer to be seen: she found  herself in a long, low hall, which was lit up by a row of lamps hanging  from the roof. There were doors all round the hall, but they were all locked; and when  Alice had been all the way down one side and up the other, trying every  door, she walked sadly down the middle, wondering how she was ever to  get out again. Suddenly she came upon a little three-legged table, all made of solid  glass; there was nothing on it except a tiny golden key, and Alice's  first thought was that it might belong to one of the doors of the hall;  but, alas! either the locks were too large, or the key was too small,  but at any rate it would not open any of them.")
